sudo: false

language: node_js

node_js:
  - "8"

os:
  - osx
  - linux

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

before_install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      sudo apt-get --assume-yes install libsecret-1-0 xclip;
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm run lint --silent
  - npm test

jobs:
  include:
    - stage: release
      os: linux
      script: npm run semantic-release
