name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published

jobs:
  lint-test:
    name: Lint, Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Cache dependencies
        id: dependencies-cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: dependencies-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.dependencies-cache.outputs.cache-hit != 'true'
        run: yarn install --no-progress --no-lockfile --ignore-optional

      - name: Run code analysis
        run: yarn run lint
        if: runner.os != 'windows'

      - name: Run tests
        run: xvfb-run -a yarn run test
        if: runner.os == 'Linux'

      - name: Run tests
        run: yarn run test
        if: runner.os != 'Linux'

      - name: Store test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports-{{ matrix.os }}
          path: test-reports

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ lint-test ]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          branch: master
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ lint-test ]
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - uses: actions/cache@v2
        id: dependencies-cache
        with:
          path: ./node_modules
          key: dependencies-${{ hashFiles('yarn.lock') }}

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          packagePath: ./dist
